services:
  httpd:
    build:
      context: .
      target: ets
    environment:
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - DB_DATABASE=ets
      - DB_HOST=mariadb
      - DB_PASSWORD=ets
      - DB_USER=ets
      - EMAIL_SENDER_TRANSPORT=SMTP
      - EMAIL_SENDER_TRANSPORT_helo=${SMTP_HELO}
      - EMAIL_SENDER_TRANSPORT_host=${SMTP_HOST:-mailcatcher}
      - EMAIL_SENDER_TRANSPORT_port=${SMTP_PORT:-1025}
      - EMAIL_SENDER_TRANSPORT_sasl_password=${SMTP_PASSWORD-}
      - EMAIL_SENDER_TRANSPORT_sasl_username=${SMTP_USERNAME-}
      - EMAIL_SENDER_TRANSPORT_ssl=maybestarttls
      - ETS_BASE_URL=${ETS_BASE_URL:-http://localhost:${HTTP_EXTERNAL_PORT:-8080}}
      - GIT_HASH=${GIT_HASH?Run 'source env.version' before running docker compose!}
      - GUTS_SERVER=guts:31337
      - HTTP_EXTERNAL_PORT=${HTTP_EXTERNAL_PORT:-8080}
      - OIDC_CLIENT_ID
      - OIDC_PROVIDER
      - OIDC_SECRET
      - TZ=${TZ:-Europe/Budapest}
      - SITENAME=${SITENAME:-DP Elektronikus Tanársegéd}
      - VERSION=${VERSION?Run 'source env.version' before running docker compose!}
    hostname: httpd
    ports:
      - 127.0.0.1:${HTTP_EXTERNAL_PORT:-8080}:80
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - ${ARCHIVE_MOUNT:-archives}:/mnt/archives
      - ${SICSTUS_LICENSE_FILE:-/dev/null}:/opt/ets/LICENSE.sicstus:ro

  mariadb:
    build:
      context: .
      target: db
    environment:
      - MARIADB_USER=ets
      - MARIADB_PASSWORD=ets
      - MARIADB_DATABASE=ets
      - MARIADB_ROOT_PASSWORD=neduddgi
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - ETS_ADMIN_NEPTUN_CODE
      - TZ=${TZ:-Europe/Budapest}
    hostname: mariadb
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  guts:
    build:
      args:
        - SICSTUS_SITENAME=${SICSTUS_SITENAME}
        - SICSTUS_LICENSE_CODE=${SICSTUS_LICENSE_CODE}
        - SICSTUS_EXPIRATION_DATE=${SICSTUS_EXPIRATION_DATE}
      context: .
      target: guts-runtime
    environment:
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - DB_DATABASE=ets
      - DB_HOST=mariadb
      - DB_PASSWORD=ets
      - DB_USER=ets
      - SMTP_HELO
      - SMTP_HOST=${SMTP_HOST:-mailcatcher}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_PASSWORD=${SMTP_PASSWORD-}
      - SMTP_USERNAME=${SMTP_USERNAME-}
      - TZ=${TZ:-Europe/Budapest}
    hostname: guts
    ports:
      - 127.0.0.1:31337:31337
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - ${GUTS_WORK_MOUNT:-guts}:/opt/guts/work

  mailcatcher:
    image: dockage/mailcatcher
    environment:
      - TZ=${TZ:-Europe/Budapest}
    hostname: mailcatcher
    ports:
      - 127.0.0.1:1080:1080
    profiles:
      - develop
    restart: unless-stopped

  keycloak:
    build:
      context: .
      target: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:${OIDC_EXTERNAL_PORT:-8081}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - TZ=${TZ:-Europe/Budapest}
    hostname: keycloak
    ports:
      - 127.0.0.1:${OIDC_EXTERNAL_PORT:-8081}:8080
    profiles:
      - develop
    restart: unless-stopped

volumes:
  archives:
  db:
  guts:
