services:
  httpd:
    build:
      context: .
      target: ets
      args:
        - ETS_BASE_URL=${ETS_BASE_URL:-http://localhost:${HTTP_EXTERNAL_PORT:-8080}}
        - OIDC_PROVIDER=${OIDC_PROVIDER}
        - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
        - OIDC_SECRET=${OIDC_SECRET}
    environment:
      - DB_HOST=mariadb
      - DB_USER=ets
      - DB_PASSWORD=ets
      - DB_DATABASE=ets
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - SITENAME=${SITENAME:-DP Elektronikus Tanársegéd}
      - EMAIL_SENDER_TRANSPORT=SMTP
      - EMAIL_SENDER_TRANSPORT_host=${SMTP_HOST:-mailcatcher}
      - EMAIL_SENDER_TRANSPORT_port=${SMTP_PORT:-1025}
      - EMAIL_SENDER_TRANSPORT_sasl_username=${SMTP_USERNAME-}
      - EMAIL_SENDER_TRANSPORT_sasl_password=${SMTP_PASSWORD-}
      - ETS_BASE_URL
      - OIDC_PROVIDER
    ports:
      - ${HTTP_EXTERNAL_PORT:-8080}:80
    profiles:
      - develop
      - live
    restart: unless-stopped
    #volumes:

  mariadb:
    build:
      context: .
      target: db
    environment:
      - MARIADB_USER=ets
      - MARIADB_PASSWORD=ets
      - MARIADB_DATABASE=ets
      - MARIADB_ROOT_PASSWORD=neduddgi
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - ETS_ADMIN_NEPTUN_CODE
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - 1080:1080
    profiles:
      - develop
    restart: unless-stopped

  keycloak:
    build:
      context: .
      target: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:${OIDC_EXTERNAL_PORT:-8081}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
    command: ["start-dev", "--import-realm"]
    ports:
      - ${OIDC_EXTERNAL_PORT:-8081}:8080
    profiles:
      - develop
    restart: unless-stopped

volumes:
  db:
