services:
  httpd:
    build:
      context: .
      target: ets
    environment:
      - DB_HOST=mariadb
      - DB_USER=ets
      - DB_PASSWORD=ets
      - DB_DATABASE=ets
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - SITENAME=${SITENAME:-DP Elektronikus Tanársegéd}
      - EMAIL_SENDER_TRANSPORT=SMTP
      - EMAIL_SENDER_TRANSPORT_host=${SMTP_HOST:-mailcatcher}
      - EMAIL_SENDER_TRANSPORT_port=${SMTP_PORT:-1025}
    ports:
      - ${HTTP_EXTERNAL_PORT:-8080}:80
    profiles:
      - develop
      - live
    restart: unless-stopped
    #volumes:

  mariadb:
    build:
      context: .
      target: db
    environment:
      - MARIADB_USER=ets
      - MARIADB_PASSWORD=ets
      - MARIADB_DATABASE=ets
      - MARIADB_ROOT_PASSWORD=neduddgi
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - ETS_ADMIN_PASSWORD
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - 1080:1080
    profiles:
      - develop
    restart: unless-stopped

volumes:
  db:
