services:
  httpd:
    build:
      context: .
      target: ets
    environment:
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - DB_DATABASE=ets
      - DB_HOST=mariadb
      - DB_PASSWORD=ets
      - DB_USER=ets
      - EMAIL_SENDER_TRANSPORT=SMTP
      - EMAIL_SENDER_TRANSPORT_host=${SMTP_HOST:-mailcatcher}
      - EMAIL_SENDER_TRANSPORT_port=${SMTP_PORT:-1025}
      - EMAIL_SENDER_TRANSPORT_sasl_password=${SMTP_PASSWORD-}
      - EMAIL_SENDER_TRANSPORT_sasl_username=${SMTP_USERNAME-}
      - ETS_BASE_URL=${ETS_BASE_URL:-http://localhost:${HTTP_EXTERNAL_PORT:-8080}}
      - HTTP_EXTERNAL_PORT=${HTTP_EXTERNAL_PORT:-8080}
      - OIDC_CLIENT_ID
      - OIDC_PROVIDER
      - OIDC_SECRET
      - SITENAME=${SITENAME:-DP Elektronikus Tanársegéd}
    ports:
      - 127.0.0.1:${HTTP_EXTERNAL_PORT:-8080}:80
    profiles:
      - develop
      - live
    restart: unless-stopped
    #volumes:

  mariadb:
    build:
      context: .
      target: db
    environment:
      - MARIADB_USER=ets
      - MARIADB_PASSWORD=ets
      - MARIADB_DATABASE=ets
      - MARIADB_ROOT_PASSWORD=neduddgi
      - CONTACT=${CONTACT:-dp@iit.bme.hu}
      - ETS_ADMIN_NEPTUN_CODE
    profiles:
      - develop
      - live
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - 127.0.0.1:1080:1080
    profiles:
      - develop
    restart: unless-stopped

  keycloak:
    build:
      context: .
      target: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:${OIDC_EXTERNAL_PORT:-8081}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
    command: ["start-dev", "--import-realm"]
    ports:
      - 127.0.0.1:${OIDC_EXTERNAL_PORT:-8081}:8080
    profiles:
      - develop
    restart: unless-stopped

volumes:
  db:
