#!/bin/bash
set -euo pipefail

# check for running container
if [[ -z $(docker compose ps -q guts) ]]; then
    echo 'Make sure the guts container is up by running the following command:'
    echo '$ docker compose up -d guts'
    exit 1
fi

dce="docker compose exec -T guts"
cmd="${1-help}"; shift || true
case $cmd in
    (help)
        cut -c13- <<'        EOF'
            Usage: guts-docker <command> <args>...

            Available commands:

              help
                       print this help screen
              bash|sh|shell
                       run a shell in the guts container
              daemons  <sub-command>
                       run a daemons command in the guts container
        EOF
        $dce ./guts help | tail +4
        cut -c13- <<'        EOF'
              kill     <config-file>
                       kill a running testd daemon immediately
        EOF
        ;;
    (bash|sh|shell)
        # invoke shell or guts command directly
        exec docker compose exec guts /bin/bash "$@"
        ;;
    (daemons)
        # invoke daemons utility
        exec $dce ./daemons "$@"
        ;;
    (start)
        # run testd command protected by daemons script
        exec $dce ./daemons start ./guts start "$@"
        ;;
    (kill)
        # stop running testd command protected by daemons script
        exec $dce ./daemons kill ./guts start "$@"
        ;;
    (*)
        # run all other commands with guts, without allocating a terminal
        # (allows forwarding of stdin)
        exec $dce ./guts "$cmd" "$@"
        ;;
esac
